In [1]:
# 为这个项目导入需要的库
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
# 允许为DataFrame使用display()
from IPython.display import display 
from matplotlib import pyplot as plt
import networkx as nx


## 个人数据（已清洗）

In [2]:
#清洗好的individual data
data_financial = pd.read_csv('data_cleaned2.csv',header=0,error_bad_lines=False)

data_user=pd.read_csv('extraData/NFA_feature_out.csv')
#将inf数据设置为nan
data_user[np.isinf(data_user)] = np.nan
#设置index
data_financial = data_financial.set_index("id_index")
data_user=data_user.set_index("id")
#数据合并
data1=pd.merge(data_user,data_financial,left_index=True,right_index=True)
#删除nan数据
data1=data1.dropna(axis=0,how='any')
#individual data前5条
print('前5条:')
pd.set_option('display.max_columns', None)
display(data_financial.head(5))
print("========")


#数据规模
print('数据规模：{}'.format(data_financial.shape))
print("")
print("========")

#标签比例
print('标签比例：')
display(pd.value_counts(data1['target_tov']))
print("========")

#有空值的列——无
print('有空值的列:无')
print(data1.columns[data1.isna().any()])
print("========")


前5条:


class  date_month  target_tov  acc_cnt  cre_type  ucreate_days  \
id_index                                                                    
389592041      0      201803           0        1       1.0          1117   
387768341      1      201801           1        1       1.0           504   
385949113      1      201801           1        2       1.0           111   
378007338      0      201803           0        1       1.0          1613   
375796863      0      201801           0        1       1.0          1121   

           user_type  wx_firdate_days  wx_regtime_days  wxu_sex  \
id_index                                                          
389592041        1.0            757.0             1140      2.0   
387768341        1.0            483.0              594      1.0   
385949113        1.0             72.0              130      2.0   
378007338        1.0            758.0             2161      2.0   
375796863        1.0            777.0             1830      2.0   

           if_bindmobile_safe_max  wxu_bindqq_safe  pay_crd_num  birth_date  \
id_index                                                                      
389592041                       1                1            1  19690814.0   
387768341                       1                1            1  19701211.0   
385949113                       1                1            1  19990615.0   
378007338                       1                1            2  19820103.0   
375796863                       1                1            2  19820427.0   

           sex  if_bindmobile_safe_min  if_chg_mob_max  if_chg_mob_min  \
id_index                                                                 
389592041  0.0                       0             0.0             0.0   
387768341  1.0                       1             0.0             0.0   
385949113  1.0                       0             1.0             0.0   
378007338  0.0                       0             0.0             0.0   
375796863  0.0                       0             0.0             0.0   

           if_chg_qq_max  if_chg_qq_min  if_chg_dev_max  if_chg_dev_min  \
id_index                                                                  
389592041            0.0            0.0             0.0             0.0   
387768341            0.0            0.0             0.0             0.0   
385949113            1.0            0.0             1.0             0.0   
378007338            0.0            0.0             1.0             0.0   
375796863            0.0            0.0             1.0             0.0   

           chg_dev_cnt_max  chg_dev_cnt_min  if_op_safdev_max  \
id_index                                                        
389592041              1.0              1.0               0.0   
387768341              1.0              1.0               0.0   
385949113              4.0              1.0           16384.0   
378007338              5.0              1.0           16384.0   
375796863              4.0              1.0           16384.0   

           if_op_safdev_min  unbind_max  unbind_min  old_acc_sus_max  \
id_index                                                               
389592041               0.0           0           0                0   
387768341               0.0           1           0                1   
385949113               0.0           1           0                1   
378007338           16384.0           1           1                0   
375796863           16384.0           1           1                1   

           old_acc_sus_min  maochi_lvl_max  maochi_lvl_min  dev_acc_cnt_max  \
id_index                                                                      
389592041                0               4               4                0   
387768341                1               4               3                0   
385949113                0               3               1                0   
378007338                0               4    

数据规模：(9098, 447)

标签比例：


0    4291
1    2831
Name: target_tov, dtype: int64

有空值的列:无
Index([], dtype='object')


In [3]:
#统计指标：
data1.describe()

out_amount_nd  out_frequency_nd  out_amount_ss  out_frequency_ss  \
count    7122.000000       7122.000000    7122.000000       7122.000000   
mean       -0.254459         -6.116067       0.180345        -19.543886   
std         0.486309          7.615371       0.587149         32.843795   
min       -20.829719        -79.064204      -0.011067      -2121.341320   
25%        -0.292123         -9.093426       0.002921        -25.243636   
50%        -0.107809         -4.846747       0.023931        -12.998771   
75%        -0.038423         -2.085140       0.126105         -5.686768   
max        -0.000269        184.477311      21.431056         -0.050579   

            class     date_month   target_tov      acc_cnt     cre_type  \
count  7122.00000    7122.000000  7122.000000  7122.000000  7122.000000   
mean      0.48975  201801.948189     0.397501     1.497894     0.993682   
std       0.49993       0.864657     0.489415     0.834456     0.079243   
min       0.00000  201801.000000     0.000000     1.000000     0.000000   
25%       0.00000  201801.000000     0.000000     1.000000     1.000000   
50%       0.00000  201802.000000     0.000000     1.000000     1.000000   
75%       1.00000  201803.000000     1.000000     2.000000     1.000000   
max       1.00000  201803.000000     1.000000    31.000000     1.000000   

       ucreate_days    user_type  wx_firdate_days  wx_regtime_days  \
count   7122.000000  7122.000000      7122.000000      7122.000000   
mean     644.418422     0.997613       563.585791       979.434709   
std      436.266116     0.048802       355.320129       966.990359   
min      -30.000000     0.000000       -30.000000       -30.000000   
25%      224.000000     1.000000       230.000000       334.000000   
50%      679.500000     1.000000       594.000000       852.000000   
75%     1121.000000     1.000000       855.000000      1549.750000   
max     1638.000000     1.000000      1263.000000     17591.000000   

           wxu_sex  if_bindmobile_safe_max  wxu_bindqq_safe  pay_crd_num  \
count  7122.000000             7122.000000      7122.000000  7122.000000   
mean      1.450295                0.966723         0.986240     1.464195   
std       0.543683                0.179372         0.116502     0.744155   
min       0.000000                0.000000         0.000000     0.000000   
25%       1.000000                1.000000         1.000000     1.000000   
50%       1.000000                1.000000         1.000000     1.000000   
75%       2.000000                1.000000         1.000000     2.000000   
max       2.000000                1.000000         1.000000     8.000000   

         birth_date          sex  if_bindmobile_safe_min  if_chg_mob_max  \
count  7.122000e+03  7122.000000             7122.000000     7122.000000   
mean   1.987622e+07     0.639146                0.275344        0.303286   
std    8.584597e+04     0.480282                0.446719        0.459710   
min    1.958053e+07     0.000000                0.000000        0.000000   
25%    1.982082e+07     0.000000                0.000000        0.000000   
50%    1.989071e+07     1.000000                0.000000        0.000000   
75%    1.994121e+07     1.000000                1.000000        1.000000   
max    2.005012e+07     1.000000                1.000000        1.000000   

       if_chg_mob_min  if_chg_qq_max  if_chg_qq_min  if_chg_dev_max  \
count     7122.000000    7122.000000    7122.000000     7122.000000   
mean         0.000983       0.051952       0.000140        0.834457   
std          0.031338       0.221945       0.011849        0.371696   
min          0.000000       0.000000       0.000000        0.000000   
25%          0.000000       0.000000       0.000000        1.000000   
50%          0.000000       0.000000       0.000000        1.000000   
75%          0.000000       0.000000       0.000000        1.000000   
max          1.000000       1.000000       1.000000        1.000000   

       if_chg_

## 划分训练集、测试集

In [4]:
# TODO：将特征和标签分为两个数据集

x=data1[data1.columns.difference(['target_tov'])]
y=data1['target_tov']

# TODO：将数据集划分为训练集和测试集
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

## 未筛选特征进行分类lr，xgb


In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

lr = LogisticRegression()                                        # 实例化一个LR模型
lr.fit(x_train,y_train)                                          # 训练模型
y_prob = lr.predict_proba(x_test)[:,1]                           # 预测1类的概率
y_pred = lr.predict(x_test)                                      # 模型对测试集的预测结果

from sklearn import metrics
print ('AUC: %.4f' % metrics.roc_auc_score(y_test,y_prob))
print ('ACC: %.4f' % metrics.accuracy_score(y_test,y_pred))
print ('Recall: %.4f' % metrics.recall_score(y_test,y_pred))
print ('F1-score: %.4f' %metrics.f1_score(y_test,y_pred))
print ('Precesion: %.4f' %metrics.precision_score(y_test,y_pred))
metrics.confusion_matrix(y_test,y_pred)

AUC: 0.6176
ACC: 0.6154
Recall: 0.1715
F1-score: 0.2674
Precesion: 0.6061


g:\pycharmvenvs\jupyterwork\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([[777,  65],
       [483, 100]], dtype=int64)

In [6]:
from xgboost.sklearn import XGBClassifier
params = {
    'booster': 'gbtree',
    'objective': 'multi:softmax',  # 多分类的问题
    'num_class': 2,               # 类别数，与 multisoftmax 并用
    'gamma': 0.1,                  # 用于控制是否后剪枝的参数,越大越保守，一般0.1、0.2这样子。
    'max_depth': 12,               # 构建树的深度，越大越容易过拟合
    'lambda': 2,                   # 控制模型复杂度的权重值的L2正则化项参数，参数越大，模型越不容易过拟合。
    'subsample': 0.7,              # 随机采样训练样本
    'colsample_bytree': 0.7,       # 生成树时进行的列采样
    'min_child_weight': 3,
    'silent': 1,                   # 设置成1则没有运行信息输出，最好是设置为0.
    'eta': 0.007,                  # 如同学习率
    'seed': 1000,
    'nthread': 4,                  # cpu 线程数
}
num_round = 10
import xgboost as xgb
dtrain = xgb.DMatrix(x_train, label=y_train)
dtest = xgb.DMatrix(x_test, label=y_test)
evallist = [ (dtrain, 'train')]
bst = xgb.train(params, dtrain, num_round, evallist)
y_prob = bst.predict(dtest)
y_pred = (y_prob >= 0.5)*1# AUC得分
                # 模型准确率

from sklearn import metrics
print ('AUC: %.4f' % metrics.roc_auc_score(y_test,y_prob))
print ('ACC: %.4f' % metrics.accuracy_score(y_test,y_pred))
print ('Recall: %.4f' % metrics.recall_score(y_test,y_pred))
print ('F1-score: %.4f' %metrics.f1_score(y_test,y_pred))
print ('Precesion: %.4f' %metrics.precision_score(y_test,y_pred))
metrics.confusion_matrix(y_test,y_pred)

[0]	train-merror:0.166403
[1]	train-merror:0.127962
[2]	train-merror:0.110233
[3]	train-merror:0.103388
[4]	train-merror:0.09426
[5]	train-merror:0.091452
[6]	train-merror:0.086712
[7]	train-merror:0.083377
[8]	train-merror:0.078638
[9]	train-merror:0.076005
AUC: 0.6354
ACC: 0.6702
Recall: 0.4443
F1-score: 0.5243
Precesion: 0.6395


array([[696, 146],
       [324, 259]], dtype=int64)

In [9]:
#pca降维

from sklearn.decomposition import PCA
pca=PCA(n_components=10)
X_pca_train=pca.fit_transform(x_train)
X_pca_test=pca.fit_transform(x_test)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
lr = LogisticRegression() # 实例化一个LR模型
lr.fit(X_pca_train,y_train)                                          # 训练模型
y_pca_prob = lr.predict_proba(X_pca_test)[:,1]                           # 预测1类的概率
y_pca_pred = lr.predict(X_pca_test)                                      # 模型对测试集的预测结果

from sklearn import metrics
print ('AUC: %.4f' % metrics.roc_auc_score(y_test,y_pca_prob))
print ('ACC: %.4f' % metrics.accuracy_score(y_test,y_pca_pred))
print ('Recall: %.4f' % metrics.recall_score(y_test,y_pca_pred))
print ('F1-score: %.4f' %metrics.f1_score(y_test,y_pca_pred))
print ('Precesion: %.4f' %metrics.precision_score(y_test,y_pca_pred))
metrics.confusion_matrix(y_test,y_pca_pred)

AUC: 0.5116
ACC: 0.4891
Recall: 0.6021
F1-score: 0.4909
Precesion: 0.4144


array([[346, 496],
       [232, 351]], dtype=int64)

In [11]:
from xgboost.sklearn import XGBClassifier
params = {
    'booster': 'gbtree',
    'objective': 'multi:softmax',  # 多分类的问题
    'num_class': 2,               # 类别数，与 multisoftmax 并用
    'gamma': 0.1,                  # 用于控制是否后剪枝的参数,越大越保守，一般0.1、0.2这样子。
    'max_depth': 12,               # 构建树的深度，越大越容易过拟合
    'lambda': 2,                   # 控制模型复杂度的权重值的L2正则化项参数，参数越大，模型越不容易过拟合。
    'subsample': 0.7,              # 随机采样训练样本
    'colsample_bytree': 0.7,       # 生成树时进行的列采样
    'min_child_weight': 3,
    'silent': 1,                   # 设置成1则没有运行信息输出，最好是设置为0.
    'eta': 0.007,                  # 如同学习率
    'seed': 1000,
    'nthread': 4,                  # cpu 线程数
}
num_round = 10
import xgboost as xgb
dtrain = xgb.DMatrix(X_pca_train, label=y_train)
dtest = xgb.DMatrix(X_pca_test, label=y_test)
evallist = [ (dtrain, 'train')]
bst = xgb.train(params, dtrain, num_round, evallist)
y_pca_prob = bst.predict(dtest)
y_pca_pred = (y_pca_prob >= 0.5)*1# AUC得分
                # 模型准确率

from sklearn import metrics
print ('AUC: %.4f' % metrics.roc_auc_score(y_test,y_pca_prob))
print ('ACC: %.4f' % metrics.accuracy_score(y_test,y_pca_pred))
print ('Recall: %.4f' % metrics.recall_score(y_test,y_pca_pred))
print ('F1-score: %.4f' %metrics.f1_score(y_test,y_pca_pred))
print ('Precesion: %.4f' %metrics.precision_score(y_test,y_pca_pred))
metrics.confusion_matrix(y_test,y_pca_pred)

[0]	train-merror:0.258908
[1]	train-merror:0.232403
[2]	train-merror:0.215903
[3]	train-merror:0.213797
[4]	train-merror:0.2066
[5]	train-merror:0.201861
[6]	train-merror:0.197648
[7]	train-merror:0.192031
[8]	train-merror:0.190451
[9]	train-merror:0.190627
AUC: 0.5415
ACC: 0.5860
Recall: 0.2967
F1-score: 0.3697
Precesion: 0.4901


array([[662, 180],
       [410, 173]], dtype=int64)

## 随机森林特征选择

In [12]:
## TODO：使用随机森林进行特征选择，首先在训练集拟合随机森林模型

rf = RandomForestClassifier(n_estimators=400,max_depth=10,verbose=1)
rf.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 400 out of 400 | elapsed:    9.8s finished


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=400,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=1, warm_start=False)

In [13]:
imp=np.argsort(rf.feature_importances_)[::-1]
print("前230个特征的重要性贡献值：")
print(sum(rf.feature_importances_[imp[:230]]))
print('他们是：')
print(x_train.columns[list(np.argsort(rf.feature_importances_)[::-1])[:230]])
#前230个特征可以让贡献率和到达90%
X_RF_train=x_train[x_train.columns[list(np.argsort(rf.feature_importances_)[::-1])[:230]]]
X_RF_train.shape
X_RF_test=x_test[x_train.columns[list(np.argsort(rf.feature_importances_)[::-1])[:230]]]


前230个特征的重要性贡献值：
0.8951394214877716
他们是：
Index(['wx_regtime_days', 'ucreate_days', 'fpay_days', 'cre_crd_amt',
       'em_ttl_cnt', 'tf_em_ttl_cnt', 'wx_firdate_days', 'wxu_activity_score',
       'tf_fpay_ttl_amt', 'fpay_ttl_amt',
       ...
       'hb_fpay_days_max', 'o2o_cnt', 'tencent_cnt', 'maochi_lvl_min',
       'travel_days_max', 'tf_rev_days_more1000_max', 'tf_bpay_days_min',
       'am_days_min', 'vir_am_days', 'hb_fpay_days'],
      dtype='object', length=230)


In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
lr = LogisticRegression() # 实例化一个LR模型
lr.fit(X_RF_train,y_train)                                          # 训练模型
y_RF_prob = lr.predict_proba(X_RF_test)[:,1]                           # 预测1类的概率
y_RF_pred = lr.predict(X_RF_test)                                      # 模型对测试集的预测结果

from sklearn import metrics
print ('AUC: %.4f' % metrics.roc_auc_score(y_test,y_RF_prob))
print ('ACC: %.4f' % metrics.accuracy_score(y_test,y_RF_pred))
print ('Recall: %.4f' % metrics.recall_score(y_test,y_RF_pred))
print ('F1-score: %.4f' %metrics.f1_score(y_test,y_RF_pred))
print ('Precesion: %.4f' %metrics.precision_score(y_test,y_RF_pred))
metrics.confusion_matrix(y_test,y_RF_pred)

AUC: 0.6205
ACC: 0.5965
Recall: 0.0326
F1-score: 0.0620
Precesion: 0.6333


g:\pycharmvenvs\jupyterwork\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([[831,  11],
       [564,  19]], dtype=int64)

In [17]:
from xgboost.sklearn import XGBClassifier
params = {
    'booster': 'gbtree',
    'objective': 'multi:softmax',  # 多分类的问题
    'num_class': 2,               # 类别数，与 multisoftmax 并用
    'gamma': 0.1,                  # 用于控制是否后剪枝的参数,越大越保守，一般0.1、0.2这样子。
    'max_depth': 12,               # 构建树的深度，越大越容易过拟合
    'lambda': 2,                   # 控制模型复杂度的权重值的L2正则化项参数，参数越大，模型越不容易过拟合。
    'subsample': 0.7,              # 随机采样训练样本
    'colsample_bytree': 0.7,       # 生成树时进行的列采样
    'min_child_weight': 3,
    'silent': 1,                   # 设置成1则没有运行信息输出，最好是设置为0.
    'eta': 0.007,                  # 如同学习率
    'seed': 1000,
    'nthread': 4,                  # cpu 线程数
}
num_round = 10
import xgboost as xgb
dtrain = xgb.DMatrix(X_RF_train, label=y_train)
dtest = xgb.DMatrix(X_RF_test, label=y_test)
evallist = [ (dtrain, 'train')]
bst = xgb.train(params, dtrain, num_round, evallist)
y_RF_prob = bst.predict(dtest)
y_RF_pred = (y_RF_prob >= 0.5)*1# AUC得分
                # 模型准确率

from sklearn import metrics
print ('AUC: %.4f' % metrics.roc_auc_score(y_test,y_RF_prob))
print ('ACC: %.4f' % metrics.accuracy_score(y_test,y_RF_pred))
print ('Recall: %.4f' % metrics.recall_score(y_test,y_RF_pred))
print ('F1-score: %.4f' %metrics.f1_score(y_test,y_RF_pred))
print ('Precesion: %.4f' %metrics.precision_score(y_test,y_RF_pred))
metrics.confusion_matrix(y_test,y_RF_pred)

[0]	train-merror:0.174653
[1]	train-merror:0.128313
[2]	train-merror:0.111287
[3]	train-merror:0.103388
[4]	train-merror:0.098122
[5]	train-merror:0.092856
[6]	train-merror:0.091803
[7]	train-merror:0.087239
[8]	train-merror:0.083026
[9]	train-merror:0.080393
AUC: 0.6321
ACC: 0.6660
Recall: 0.4460
F1-score: 0.5221
Precesion: 0.6295


array([[689, 153],
       [323, 260]], dtype=int64)

## 当前来看，随机森林特征选择，加xgb效果最好，进一步加入归一化

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
# ss = StandardScaler()
ss = MinMaxScaler()
X_RF_st_train = ss.fit_transform(X_RF_train)
X_RF_st_test = ss.fit_transform(X_RF_test)
from xgboost.sklearn import XGBClassifier
params = {
    'booster': 'gbtree',
    'objective': 'multi:softmax',  # 多分类的问题
    'num_class': 2,               # 类别数，与 multisoftmax 并用
    'gamma': 0.1,                  # 用于控制是否后剪枝的参数,越大越保守，一般0.1、0.2这样子。
    'max_depth': 12,               # 构建树的深度，越大越容易过拟合
    'lambda': 2,                   # 控制模型复杂度的权重值的L2正则化项参数，参数越大，模型越不容易过拟合。
    'subsample': 0.7,              # 随机采样训练样本
    'colsample_bytree': 0.7,       # 生成树时进行的列采样
    'min_child_weight': 3,
    'silent': 1,                   # 设置成1则没有运行信息输出，最好是设置为0.
    'eta': 0.007,                  # 如同学习率
    'seed': 1000,
    'nthread': 4,                  # cpu 线程数
}
num_round = 10
import xgboost as xgb
dtrain = xgb.DMatrix(X_RF_st_train, label=y_train)
dtest = xgb.DMatrix(X_RF_st_test, label=y_test)
evallist = [ (dtrain, 'train')]
bst = xgb.train(params, dtrain, num_round, evallist)
y_RF_prob = bst.predict(dtest)
y_RF_pred = (y_RF_prob >= 0.5)*1# AUC得分
                # 模型准确率

from sklearn import metrics
print ('AUC: %.4f' % metrics.roc_auc_score(y_test,y_RF_prob))
print ('ACC: %.4f' % metrics.accuracy_score(y_test,y_RF_pred))
print ('Recall: %.4f' % metrics.recall_score(y_test,y_RF_pred))
print ('F1-score: %.4f' %metrics.f1_score(y_test,y_RF_pred))
print ('Precesion: %.4f' %metrics.precision_score(y_test,y_RF_pred))
metrics.confusion_matrix(y_test,y_RF_pred)

[0]	train-merror:0.17518
[1]	train-merror:0.12884
[2]	train-merror:0.111111
[3]	train-merror:0.103212
[4]	train-merror:0.098473
[5]	train-merror:0.092856
[6]	train-merror:0.093734
[7]	train-merror:0.088994
[8]	train-merror:0.085835
[9]	train-merror:0.079516
AUC: 0.6335
ACC: 0.6526
Recall: 0.5283
F1-score: 0.5545
Precesion: 0.5833


array([[622, 220],
       [275, 308]], dtype=int64)